[package]
name = "structured-jsonish"
version = "0.1.0"
edition = "2021"

[dependencies]
json_partial.workspace = true
common.workspace = true
futures.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
schemars.workspace = true